import './globals.css';
import { getEvents } from '@/database/events';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import EventsForm from './components/event/EventForm';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const events = await getEvents();

type Props = {
  children: ReactNode;
};
export default async function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <tbody>
        <h1 className="heading">Sport Calendar</h1>
        <div className="container">
          <p>Please fill the fields:</p>
        </div>
        <div>
          <EventsForm events={events} />
        </div>

        {/* Table for user can see after filling the form for Date, Day, Event, Teams */}
        {children}
        {/* Categorizing sports */}
        <div className="forms">
          <h2>Sports</h2>
          <ul>
            <li>Football</li>
            <li>Basketball</li>
            <li>Baseball</li>
            <li>Boxing</li>
            <li>Gold</li>
          </ul>
        </div>
      </tbody>
    </html>
  );
}
