import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import { Calendar } from 'react-calendar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};
export default async function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <tbody>
        <h1 className="heading">Sport Calendar</h1>
        <div className="container">
          <p>Please fill the fields:</p>
          <div className="inputField">
            {/* This is Calendar component */}
            {/* Create form inputField for user to input data */}
            <p>
              Date: <input placeholder="Please write a date" />
            </p>
            <p>
              Time: <input placeholder="Time" />
            </p>

            <p>
              Sport: <input />
            </p>
            <p>
              Team: <input />
            </p>
            {/* User can press Submit button after filling the form  */}

            <button>Submit</button>
          </div>
        </div>

        {/* Table for user can see after filling the form for Date, Day, Event, Teams */}
        {children}

        <div className="forms">
          <h2>Sports</h2>
          <ul>
            <li>Football</li>
            <li>Basketball</li>
            <li>Baseball</li>
            <li>Boxing</li>
            <li>Gold</li>
          </ul>
        </div>
      </tbody>
    </html>
  );
}
