import './globals.css';
import { saveData } from '@/database/events';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import EventsForm from './components/event/EventForm';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};
export default async function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body>
        <h1 className="heading">Sport Calendar</h1>
        <div className="container">
          <p>Please fill the fields:</p>
          <button>Sort</button>
        </div>

        {/* Table for user can see after filling the form for Date, Day, Event, Teams */}
        {/* Categorizing sports */}
        <div>
          <EventsForm events={[]} />
        </div>
        {children}
      </body>
    </html>
  );
}
